language: php

php:
  - 7.1

matrix:
  fast_finish: true

before_script:
  - composer update --dev

script: vendor/bin/phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - prager.adam87@gmail.com
