language: php

php:
  - 5.3
  - 5.6

env:
  - SYMFONY_VERSION=2.3.*
  - SYMFONY_VERSION=2.8.*
  - SYMFONY_VERSION=3.0.*

matrix:
  fast_finish: true
  exclude:
    - php: 5.3
      env: SYMFONY_VERSION=3.0.*

before_script:
  - composer require symfony/symfony:${SYMFONY_VERSION} --no-update
  - composer update --dev

script: phpunit

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    - prager.adam87@gmail.com
